name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: |
          echo "Hello Dear"
          echo " Bye"
      - name: Print Welocme Again
        run: echo "Welcome Again"
